# Generated by Django 5.2.1 on 2025-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_alter_subject_options_remove_subject_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
