# Generated by Django 5.2.1 on 2025-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
