# Generated by Django 5.2.1 on 2025-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_questionsession_sessionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquestion',
            name='answer_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
